#!/usr/bin/env python3
import os
import sys
import subprocess

# Detectar la carpeta HOME del usuario que ejecuta APUS
HOME = os.path.expanduser("~")

# Ruta real donde está APUS dentro del usuario
APUS_DIR = os.path.join(HOME, "apus")
APUS_MAIN = os.path.join(APUS_DIR, "apus.py")

# Ejecutar apus.py con los argumentos del usuario
subprocess.run(["python3", APUS_MAIN] + sys.argv[1:])

